// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-tcp
using ReactNativeTcp;

// Namespaces from net
using ReactNativeTcp;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from react-native-tcp
            packageProviders.Add(new ReactNativeTcp.ReactPackageProvider());
            // IReactPackageProviders from net
            packageProviders.Add(new ReactNativeTcp.ReactPackageProvider());
        }
    }
}
